env: "local" # local, dev, prod - type of machine where server is running. based on this can change behaviour somewhere?
db: 
  host: "localhost" # path to storage (with sqlite it's quite simple)
  port: 5432
  name: "postgres"
  username: postgres
  password: postgres
http_server:
  address: "localhost:8082"
  timeout: 4s # timeout to read/write response/request
  idle_timeout: 60s # timeout to close connection if no actions from client